DO
$$BEGIN
IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'masteromni') THEN
    EXECUTE 'REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA pg_catalog FROM masteromni';
    EXECUTE 'DROP ROLE IF EXISTS masteromni';
END IF;
IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'sberpg') THEN
    EXECUTE 'REVOKE ALL ON ALL FUNCTIONS IN SCHEMA pg_catalog FROM sberpg';
    EXECUTE 'DROP ROLE IF EXISTS sberpg';
END IF;
END$$;
DROP USER IF EXISTS pstgcmdb;